# Generated by Django 4.0.5 on 2022-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/default.png', upload_to='profiles/', verbose_name='Profile Picture'),
        ),
    ]
